### ISSUE TITLE
[Feature Request] Add cache for paragraph translations.

### ISSUE THREAD

**Issue by BluePadge** [Elilif/emacs-immersive-translate#3]
Thank you for your work. Reading foreign language materials in Nov and Elfeed has become a much better experience.

I have a request that I hope you could consider: **adding paragraph translation caching**. This feature is available in the web version. With this, when a paragraph of text has been translated once, if it's opened again for reading, it can reduce some cost consumption, especially when using ChatGPT as the backend.

**Comment by Elilif** [comment]
I believe this has been implemented. You can try it out to see if there are any
bugs. If there are none, please close this issue. Thank you.
